### ISSUE TITLE
'TextureVisuals' object has no attribute 'face_colors'

### ISSUE THREAD

**Issue by stephane-caron** [clemense/yourdfpy#10]
Happens when loading [this model](https://github.com/Gepetto/example-robot-data/blob/master/robots/kinova_description/robots/kinova.urdf):

```
$ yourdfpy example-robot-data/robots/kinova_description/robots/kinova.urdf         ✔ 
Traceback (most recent call last):
  File "/home/nelson/.local/bin/yourdfpy", line 8, in <module>
    sys.exit(run())
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/viz.py", line 106, in run
    main(sys.argv[1:])
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/viz.py", line 97, in main
    urdf_model = URDF.load(args.input)
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 788, in load
    return URDF(robot=URDF._parse_robot(xml_element=xml_root), **kwargs)
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 444, in __init__
    self._scene = self._create_scene(
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 1129, in _create_scene
    self._add_geometries_to_scene(
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 1095, in _add_geometries_to_scene
    apply_visual_color(geom, v)
  File "/home/nelson/.local/lib/python3.8/site-packages/yourdfpy/urdf.py", line 241, in apply_visual_color
    geom.visual.face_colors[:] = [
AttributeError: 'TextureVisuals' object has no attribute 'face_colors'
```

This issue was introduced in https://github.com/clemense/yourdfpy/pull/6 Should be readily fixable with an extra check.

**Comment by clemense** [comment]
Thank you!
